/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedAlertsRouteImport } from './routes/_protected/alerts'
import { Route as ProtectedApiRouteImport } from './routes/_protected/api'
import { Route as ProtectedAppRouteImport } from './routes/_protected/app'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedResearchRouteImport } from './routes/_protected/research'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedReportIdRouteImport } from './routes/_protected/report/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'
import { Route as ApiAdminNotesIndexRouteImport } from './routes/api/admin/notes/index'
import { Route as ApiAdminNotesIdRouteImport } from './routes/api/admin/notes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAlertsRoute = ProtectedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiRoute = ProtectedApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedResearchRoute = ProtectedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportIdRoute = ProtectedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIndexRoute = ApiAdminNotesIndexRouteImport.update({
  id: '/api/admin/notes/',
  path: '/api/admin/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIdRoute = ApiAdminNotesIdRouteImport.update({
  id: '/api/admin/notes/$id',
  path: '/api/admin/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/alerts': typeof ProtectedAlertsRoute
  '/api': typeof ProtectedApiRoute
  '/app': typeof ProtectedAppRoute
  '/billing': typeof ProtectedBillingRoute
  '/research': typeof ProtectedResearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/report/$id': typeof ProtectedReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/alerts': typeof ProtectedAlertsRoute
  '/api': typeof ProtectedApiRoute
  '/app': typeof ProtectedAppRoute
  '/billing': typeof ProtectedBillingRoute
  '/research': typeof ProtectedResearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/report/$id': typeof ProtectedReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/admin/notes': typeof ApiAdminNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/alerts': typeof ProtectedAlertsRoute
  '/_protected/api': typeof ProtectedApiRoute
  '/_protected/app': typeof ProtectedAppRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/research': typeof ProtectedResearchRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/report/$id': typeof ProtectedReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/app'
    | '/billing'
    | '/research'
    | '/settings'
    | '/report/$id'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/notes/'
    | '/api/admin/notes/$id'
    | '/api/admin/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/alerts'
    | '/api'
    | '/app'
    | '/billing'
    | '/research'
    | '/settings'
    | '/report/$id'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/notes'
    | '/api/admin/notes/$id'
    | '/api/admin/notes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/admin'
    | '/_protected/alerts'
    | '/_protected/api'
    | '/_protected/app'
    | '/_protected/billing'
    | '/_protected/research'
    | '/_protected/settings'
    | '/_protected/report/$id'
    | '/api/auth/$'
    | '/api/notes/$id'
    | '/api/notes/'
    | '/api/admin/notes/$id'
    | '/api/admin/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiAdminNotesIdRoute: typeof ApiAdminNotesIdRoute
  ApiAdminNotesIndexRoute: typeof ApiAdminNotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/alerts': {
      id: '/_protected/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ProtectedAlertsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api': {
      id: '/_protected/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ProtectedApiRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/app': {
      id: '/_protected/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/research': {
      id: '/_protected/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ProtectedResearchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/report/$id': {
      id: '/_protected/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ProtectedReportIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/': {
      id: '/api/admin/notes/'
      path: '/api/admin/notes'
      fullPath: '/api/admin/notes/'
      preLoaderRoute: typeof ApiAdminNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/$id': {
      id: '/api/admin/notes/$id'
      path: '/api/admin/notes/$id'
      fullPath: '/api/admin/notes/$id'
      preLoaderRoute: typeof ApiAdminNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAlertsRoute: typeof ProtectedAlertsRoute
  ProtectedApiRoute: typeof ProtectedApiRoute
  ProtectedAppRoute: typeof ProtectedAppRoute
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedResearchRoute: typeof ProtectedResearchRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedReportIdRoute: typeof ProtectedReportIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAlertsRoute: ProtectedAlertsRoute,
  ProtectedApiRoute: ProtectedApiRoute,
  ProtectedAppRoute: ProtectedAppRoute,
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedResearchRoute: ProtectedResearchRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedReportIdRoute: ProtectedReportIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiAdminNotesIdRoute: ApiAdminNotesIdRoute,
  ApiAdminNotesIndexRoute: ApiAdminNotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
